---
- name: Writing a playbook
  hosts: linoop
  vars:
    pkg: 
       - { name: httpd, state: installed, h_state: started }
       - { name: vsftpd, state: installed, h_state: started }
  tasks:
    - name: Installing a pkg
      yum:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ pkg }}"
      notify: Starting the service
      tags: anything
      when: 
        - ansible_hostname == 'managed-node-1' 
        - ansible_os_family == 'RedHat'

    - name: show the ip address using ansible facts
      debug:
        msg: "{{ ansible_os_family }}"
      tags: check
      when: ansible_hostname == 'managed-node-2'

  handlers:
    - name: Starting the service
      service:
        name: "{{ item.name }}"
        state: "{{ item.h_state }}"
      loop: "{{ pkg }}"


    