# play1 - webservers
- name: playbook for webservers
  hosts: test
  vars:
    pkgs: 
       - { name: telnet, state: present }
       - { name: vsftpd, state: present }
       - { name: httpd, state: present }
       - { name: tree, state: absent } 

  tasks:
   - name: install packages
     yum:
       name:  "{{ item.name  }}"
       state: "{{ item.state }}"
     loop: "{{ pkgs }}" 
   
   - name: starting services
     service:
       name:  "{{ item.name }}"
       state: started
       enabled: yes
     loop: "{{ pkgs }}" 
   
   - name: add httpd service to firewall
     firewalld:
       service: http
       permanent: true
       state: enabled
       immediate: yes
